# -*- coding: utf-8 -*-
"""Regresion_Lineal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dxCy4t9R_RiJUf8qxqEY5WLY_yuCqUcg
"""

import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

from pandas.plotting import scatter_matrix

plt.style.use('seaborn')

"""#Regresión Lineal de Covid en Colombia

##Importar Datos
"""

data = pd.read_csv("covid19co_time_line.csv")
data

"""##Regresión Lineal"""

lm = smf.ols(formula="total_deceased~total_reported",data=data).fit()

lm

lm.params

"""$Y = W_0 + W_1X$

$Deceased = W_0 + W_1*Reported$

$Deceased = 19.526426 + 0.024878*Reported $
"""

lm.pvalues

lm.rsquared

lm.rsquared_adj

lm.summary()

Deceased_Pred = lm.predict(pd.DataFrame(data["total_reported"]))
Deceased_Pred

plt.scatter(x=data["total_reported"],y=data["total_deceased"],label="Real",alpha=0.7)
plt.plot(data["total_reported"],Deceased_Pred,'r',linewidth=6,label="Estimado")
plt.xlabel('Reported')
plt.ylabel('Deceased')
plt.legend()
plt.show()

"""##Regresion Lineal Multivariable"""

lm2 = smf.ols(formula="total_deceased~total_reported+total_recupered",data=data).fit()

lm2.params

"""$Deceaced = 1.982838 + 0.016272*Reported + 0.029205*Recupered$"""

lm2.pvalues

lm2.rsquared

lm2.rsquared_adj

Deceased_Pred = lm2.predict(data[["total_reported","total_recupered"]])
Deceased_Pred

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(data["total_reported"],data["total_recupered"],data["total_deceased"])
plt.xlabel("reported")
plt.ylabel("recupered")
plt.title("Datos Reales")
plt.show()

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
ax.scatter(data["total_reported"],data["total_recupered"],Deceased_Pred,c='r')
plt.xlabel("reported")
plt.ylabel("recupered")
plt.title("Datos Reales")
plt.show()